# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KeyStage1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 
  pod 'GoogleSignIn'
  # Pods for KeyStage1



  target 'KeyStage1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'KeyStage1-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KeyStage1-tvOS

  target 'KeyStage1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
